### ISSUE TITLE
Wishlist: tag and/or release packages with bloom

### ISSUE THREAD

**Issue by esteve** [astuff/platform_automation_msgs#7]
A project I'm contributing to (Autoware) is currently using these packages as Git submodules, but it'd be great if they could be released via bloom and submitted to the ROS index, so they can be installed with `apt-get`

I can help with releasing these packages if you want.

Thanks.

**Comment by JWhitleyWork** [comment]
I would be happy to! Now that we've moved `radar_msgs` and `perception_msgs` (which Autoware did not appear to use) to `astuff_sensor_msgs`, things have settled down a bit and I will create a new release for both of them in all supported ROS environments (Indigo, Kinetic, Lunar, and Melodic).

**Comment by JWhitleyWork** [comment]
Lunar is currently waiting on a package sync but all other versions should be in the ShadowFixed repos in a day or two. No word on the next Kinetic package sync (I'm assuming this is the version you care about most) but once that happens, `astuff_sensor_msgs`, `platform_automation_msgs`, and all of their respective child packages should be available for rosdep install.

**Comment by esteve** [comment]
Awesome! Thanks for the quick response.

**Comment by JWhitleyWork** [comment]
@esteve - Please be aware: This repository and the packages under it are changing names. This was necessary to make the package names less generic and was required by the OSRF guys before the packages could be released into the build farm. These changes are covered in #8. Once the PR is approved, I will re-release into the build farm.

Looking at Autoware, the package `module_comm_msgs` was the only package used by that project which contained messages in this repo. The two messages that were used - SteerMode and SpeedMode - will now live under `automotive_platform_msgs` and this will need to be changed in Autoware to use the apt installs.

Note: This should not cause any changes with the current version of Autoware because the submodule is tied to a specific commit and a clone request for the previous repo name will redirect.
